Use pep 740 release procedure

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -3,6 +3,8 @@ permissions:
   contents: read
 
 on:
+  release:
+    types: [published]
   workflow_dispatch:
     inputs:
       confirm_ref:
@@ -26,21 +28,37 @@ jobs:
   deploy_test:
     name: Verify PyPI deployment confirmation
     runs-on: ubuntu-latest
+    if: github.repository == 'qutip/qutip'
+    outputs:
+      mode: ${{ steps.mode.outputs.mode }}
     env:
-      GITHUB_REF: ${{ github.ref }}
       CONFIRM_REF: ${{ github.event.inputs.confirm_ref }}
     steps:
+      - name: Set confirmation is triggered by tag
+        if: github.event_name == 'release'
+        # TODO: set to the version when working.
+        run: echo "CONFIRM_REF=test" >> "$GITHUB_ENV"
+        # run: echo "CONFIRM_REF=$GITHUB_REF_NAME" >> "$GITHUB_ENV"
+
       - name: Compare confirmation to current reference
+        id: mode
         shell: bash
         run: |
-          [[ -z $CONFIRM_REF || $GITHUB_REF =~ ^refs/(heads|tags)/$CONFIRM_REF$ || $CONFIRM_REF == "test" ]]
+          if ! [[ -z $CONFIRM_REF || $CONFIRM_REF == "test" || $GITHUB_REF_NAME == "$CONFIRM_REF" ]]; then
+            echo "::error::confirm_ref '$CONFIRM_REF' does not match '$GITHUB_REF_NAME', 'test' or ''"
+            exit 1
+          fi
           if [[ $CONFIRM_REF == "test" ]]; then
             echo "Build and deploy to test.pypi.org."
+            mode=testpypi
           elif [[ -z $CONFIRM_REF ]]; then
             echo "Build only.  Nothing will be uploaded to PyPI."
+            mode=none
           else
             echo "Full build and deploy.  Wheels and source will be uploaded to PyPI."
+            mode=pypi
           fi
+          echo "mode=$mode" >> "$GITHUB_OUTPUT"
 
 
   build_sdist:
@@ -147,13 +165,10 @@ jobs:
           path: ./wheelhouse/*.whl
 
 
-  deploy:
-    name: "Deploy to PyPI if desired"
+  check_build:
+    name: "Check built wheels"
     needs: [deploy_test, build_sdist, build_wheels]
     runs-on: ubuntu-latest
-    env:
-      TWINE_USERNAME: __token__
-      TWINE_NON_INTERACTIVE: 1
 
     steps:
       - name: Download build artifacts to local runner
@@ -174,33 +189,94 @@ jobs:
       - uses: actions/setup-python@v7
         name: Install Python
         with:
-          python-version: '3.11'
+          python-version: '3.14'
 
       - name: Verify this is not a dev version
         shell: bash
         run: |
-          python -m pip install wheels/*-cp311-cp311-manylinux*_x86_64.whl
+          python -m pip install wheels/*-cp314-cp314-manylinux*_x86_64.whl
           python -c 'import qutip; print(qutip.__version__); assert "dev" not in qutip.__version__; assert "+" not in qutip.__version__'
 
-      # We built the zipfile for convenience distributing to Windows users on
-      # our end, but PyPI only needs the tarball.
-      - name: Upload sdist and wheels to PyPI
-        run: |
-          # The confirmation is tested explicitly in `deploy_test`, so we know
-          # it is either a missing confirmation (so we shouldn't run this job),
-          # 'test' or a valid confirmation.  We don't need to retest the value
-          #  of the confirmation, beyond checking that one existed.
-          if [ '${{ github.event.inputs.confirm_ref }}' == 'test' ]; then
-            export TWINE_REPOSITORY=testpypi
-            export TWINE_PASSWORD=${{ secrets.TESTPYPI_TOKEN }}
-          elif [ '${{ github.event.inputs.confirm_ref }}' != '' ]; then
-            export TWINE_REPOSITORY=pypi
-            export TWINE_PASSWORD=${{ secrets.PYPI_TOKEN }}
-          else
-            # Exit without deploying
-            echo "Don't update wheels"
-            exit 0
-          fi
-          echo "Deploy to $TWINE_REPOSITORY"
-          python -m pip install "twine"
-          python -m twine upload --verbose wheels/*.whl wheels/*.tar.gz
+
+  deploy_pypi:
+    name: "Deploy to PyPI if desired"
+    needs: [deploy_test, check_build]
+    if: needs.deploy_test.outputs.mode == 'pypi' && github.repository == 'qutip/qutip'
+    runs-on: ubuntu-latest
+    permissions:
+      id-token: write
+    environment:
+      name: pypi
+      url: https://pypi.org/p/qutip
+
+    steps:
+      - uses: actions/download-artifact@v8
+        with:
+          path: wheels
+          merge-multiple: true
+
+      - uses: pypa/gh-action-pypi-publish@release/v1
+        with:
+          packages-dir: wheels/
+          verbose: true
+
+
+  deploy_testpypi:
+    name: "Deploy to TestPyPI if desired"
+    needs: [deploy_test, check_build]
+    if: needs.deploy_test.outputs.mode == 'testpypi' && github.repository == 'qutip/qutip'
+    runs-on: ubuntu-latest
+    permissions:
+      id-token: write
+    environment:
+      name: testpypi
+      url: https://test.pypi.org/p/qutip
+
+    steps:
+      - uses: actions/download-artifact@v8
+        with:
+          path: wheels
+          merge-multiple: true
+
+      - uses: pypa/gh-action-pypi-publish@release/v1
+        with:
+          repository-url: https://test.pypi.org/legacy/
+          packages-dir: wheels/
+          skip-existing: true
+          verbose: true
+
+
+  github-release:
+    name: >-
+      Sign the qutip with Sigstore
+      and upload them to GitHub Release
+    needs:
+    - deploy_pypi
+    runs-on: ubuntu-latest
+    if: startsWith(github.ref, 'refs/tags/')
+
+    permissions:
+      contents: write
+      id-token: write
+
+    steps:
+      - name: Download build artifacts to local runner
+        uses: actions/download-artifact@v8
+        with:
+          path: wheels
+          merge-multiple: true
+
+      - name: Sign the dists with Sigstore
+        uses: sigstore/gh-action-sigstore-python@v3.4.0
+        with:
+          inputs: >-
+            ./wheels/*.tar.gz
+            ./wheels/*.whl
+      - name: Upload artifact signatures to GitHub Release
+        env:
+          GITHUB_TOKEN: ${{ github.token }}
+        # Upload to GitHub Release using the `gh` CLI.
+        # `dist/` contains the built packages, and the
+        # sigstore-produced signatures and certificates.
+        run: >-
+          gh release upload "$GITHUB_REF_NAME" wheels/** --repo "$GITHUB_REPOSITORY"
